# Generated by Django 4.1 on 2022-08-30 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0002_tenant_create_at_tenant_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
